name: Atx Passing variables
run-name: ${{github.run_number}} passing step/job and environment variables

on:
    push:
        branches:
            - main
jobs:
    passes-variables:
        runs-on: ubuntu-latest
        outputs:
            var-1: ${{steps.creates-variables.outputs.var_1}}
            var-2: ${{steps.creates-variables.outputs.var_2}}
        steps:
            - name: creates variables
              id: creates-variables
              run: |
                  var_1=ola
                  var_2="ola otra vez"

                    echo "var_1=${var_1}" >> $GITHUB_OUTPUT
                    echo "var_2=${var_2}" >> $GITHUB_ENV

            - name: check variables scope
              run: |
                  echo "var_1: ${{steps.creates-variables.outputs.var_1}}"
                  echo "var_2: ${{env.var_2}}"

    consumes-variables:
        runs-on: ubuntu-latest
        needs: passes-variables
        steps:
            - name: check variables scope
              run: |
                  echo "var_1: ${{needs.passes-variables.outputs.var_1}}"
                  echo "var_2: ${{env.var_2}}"
